{
 "title": "Sample Request Board",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Sample MCO Dashbord\n\n> A sample MCO dashboard built on top of custom metrics exposed through micrometer."
   }
  },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(dep_latency_timer_seconds_max{instance=\"$instance\"})",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dep_http_totalCount_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sample Request Rate",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "unit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dep_http_500_errorCount_total{instance=\"$instance\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum((sum(dep_http_totalCount_total{instance=\"$instance\"}) - sum(dep_http_500_errorCount_total{instance=\"$instance\"})))",
     "legendFormat": "success"
    }
   ]
  }
 ]
}